# Generated by Django 3.1.1 on 2020-09-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200930_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='section',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
