# Generated by Django 3.1.1 on 2020-12-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201202_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='my_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
