# Generated by Django 3.1.1 on 2020-12-02 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201202_0245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_disabled',
        ),
    ]
