# Generated by Django 3.1.1 on 2020-12-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201202_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='logo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
