# Generated by Django 3.1.1 on 2020-12-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201218_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=2048)),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('tags', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
